apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rhopp-240416-gitops
  description: This is GitOps manifest for rhopp-240416   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rhopp-240416
    janus-idp.io/tekton: rhopp-240416 
    backstage.io/kubernetes-id: rhopp-240416 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rhopp-240416
