apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhopp-240416
  janus-idp.io/tekton: rhopp-240416
  backstage.io/kubernetes-id: rhopp-240416
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhopp-240416
resources: 
- deployment.yaml
- route.yaml
- service.yaml
