apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhopp-240416
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhopp-240416 
  name: rhopp-240416
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhopp-240416
    weight: 100 
