apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhopp-240416
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhopp-240416 
  name: rhopp-240416
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhopp-240416 
